#!/bin/bash
#SBATCH --job-name=openmp
#SBATCH -N 1
##SBATCH -n 1
#SBATCH --partition=nodo.q
#SBATCH --exclusive
#SBATCH --output=kmeans-sequential-test.txt


gcc -fopenmp -Ofast kmeans.c kmeanslib.c -o ./Outputs/kmeans_sequential -lm # compile
export OMP_NUM_THREADS=4        # set number of threads
echo serial
perf stat ./kmeans_parallel test 4 imagen.bmp       # execute with perf profiler to measure time

