#!/bin/bash
#SBATCH --job-name=openmp
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --partition=nodo.q
#SBATCH --exclusive
#SBATCH --output=Outputs/par-test.txt 

gcc -fopenmp -Ofast kmeans.c kmeanslib_parallel.c -o Executables/kmeans_par -lm # Compile code
export OMP_NUM_THREADS=4 # Set number of threads

echo Execució wtff

perf stat Executables/kmeans_par test 16 imagen.bmp # Execute with perf profiler to measure time, k = 4